superpoint_localization_node:
  ros__parameters:
    sensor_mode: rgbd
    image_topic: /camera/camera/color/image_raw
    depth_topic: /camera/camera/aligned_depth_to_color/image_raw
    vocabulary_file: ""
    settings_file: ""
    superpoint_model_file: ""
    map_frame: map
    child_frame: camera_link
    publish_tf: false
    force_gray: true
    max_depth_age_sec: 1.0
    localization_only: true
